// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/grpc/proto/service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_grpc_proto_service_proto protoreflect.FileDescriptor

const file_api_grpc_proto_service_proto_rawDesc = "" +
	"\n" +
	"\x1capi/grpc/proto/service.proto\x12\x05proto\x1a!api/grpc/proto/user_message.proto2Y\n" +
	"\x12ClubManagerService\x12C\n" +
	"\n" +
	"CreateUser\x12\x18.proto.CreateUserRequest\x1a\x19.proto.CreateUserResponse\"\x00B\"Z clubmanager/api/grpc/proto;protob\x06proto3"

var file_api_grpc_proto_service_proto_goTypes = []any{
	(*CreateUserRequest)(nil),  // 0: proto.CreateUserRequest
	(*CreateUserResponse)(nil), // 1: proto.CreateUserResponse
}
var file_api_grpc_proto_service_proto_depIdxs = []int32{
	0, // 0: proto.ClubManagerService.CreateUser:input_type -> proto.CreateUserRequest
	1, // 1: proto.ClubManagerService.CreateUser:output_type -> proto.CreateUserResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_grpc_proto_service_proto_init() }
func file_api_grpc_proto_service_proto_init() {
	if File_api_grpc_proto_service_proto != nil {
		return
	}
	file_api_grpc_proto_user_message_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_grpc_proto_service_proto_rawDesc), len(file_api_grpc_proto_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_grpc_proto_service_proto_goTypes,
		DependencyIndexes: file_api_grpc_proto_service_proto_depIdxs,
	}.Build()
	File_api_grpc_proto_service_proto = out.File
	file_api_grpc_proto_service_proto_goTypes = nil
	file_api_grpc_proto_service_proto_depIdxs = nil
}
