/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './internal/**/*.templ',
    './internal/**/*_templ.go',
  ],
  theme: {
    extend: {
      colors: {
        'surface':                  '#fff8f5',
        'surface-dim':              '#e0d8d5',
        'surface-bright':           '#fff8f5',
        'surface-container-lowest': '#ffffff',
        'surface-container-low':    '#faf2ee',
        'surface-container':        '#f4ece8',
        'surface-container-high':   '#eee7e3',
        'surface-container-highest':'#e9e1dd',
        'surface-variant':          '#e9e1dd',
        'on-surface':               '#1e1b19',
        'on-surface-variant':       '#444651',
        'outline':                  '#757682',
        'outline-variant':          '#c5c5d3',
        'primary':                  '#00236f',
        'on-primary':               '#ffffff',
        'primary-container':        '#1e3a8a',
        'on-primary-container':     '#90a8ff',
        'primary-fixed':            '#dce1ff',
        'primary-fixed-dim':        '#b6c4ff',
        'inverse-primary':          '#b6c4ff',
        'secondary':                '#0058be',
        'on-secondary':             '#ffffff',
        'secondary-container':      '#2170e4',
        'on-secondary-container':   '#fefcff',
        'secondary-fixed':          '#d8e2ff',
        'secondary-fixed-dim':      '#adc6ff',
        'tertiary':                 '#5d0004',
        'on-tertiary':              '#ffffff',
        'tertiary-container':       '#87000a',
        'tertiary-fixed':           '#ffdad6',
        'tertiary-fixed-dim':       '#ffb4ab',
        'error':                    '#ba1a1a',
        'on-error':                 '#ffffff',
        'error-container':          '#ffdad6',
        'background':               '#fff8f5',
        'on-background':            '#1e1b19',
      },
      borderRadius: {
        'sm':      '0.25rem',
        'DEFAULT': '0.5rem',
        'md':      '0.75rem',
        'lg':      '1rem',
        'xl':      '1.5rem',
        'full':    '9999px',
      },
      spacing: {
        'xs':            '4px',
        'sm':            '12px',
        'md':            '24px',
        'lg':            '48px',
        'xl':            '80px',
        'gutter':        '24px',
        'container-max': '1120px',
      },
      fontFamily: {
        'headline-xl':      ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-lg':      ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-md':      ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-lg':          ['Inter', 'sans-serif'],
        'body-md':          ['Inter', 'sans-serif'],
        'body-sm':          ['Inter', 'sans-serif'],
        'data-label':       ['"JetBrains Mono"', 'monospace'],
      },
      fontSize: {
        'headline-xl':  ['40px', { lineHeight: '1.1',  letterSpacing: '-0.04em', fontWeight: '800' }],
        'headline-lg':  ['32px', { lineHeight: '1.2',  letterSpacing: '-0.03em', fontWeight: '700' }],
        'headline-md':  ['24px', { lineHeight: '1.3',  letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg':      ['18px', { lineHeight: '1.65', fontWeight: '400' }],
        'body-md':      ['16px', { lineHeight: '1.65', fontWeight: '400' }],
        'body-sm':      ['14px', { lineHeight: '1.6',  fontWeight: '400' }],
        'data-label':   ['14px', { lineHeight: '1',    fontWeight: '500' }],
      },
      maxWidth: {
        'container-max': '1120px',
      },
      boxShadow: {
        'card':      '0px 4px 20px rgba(28, 25, 23, 0.05)',
        'card-hover':'0px 8px 25px rgba(28, 25, 23, 0.08)',
        'card-md':   '0px 8px 30px rgba(28, 25, 23, 0.10)',
      },
    },
  },
  safelist: [
    'badge-active', 'badge-pending', 'badge-suspended',
    'badge-draft', 'badge-published', 'badge-archived',
  ],
  plugins: [],
}
